version: "3.8"
services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: "mongo"
    image: mongo
    ports:
      - "27017:27017"
